./wave-skim -l -n -f 5 22513 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22513.txt
./wave-skim -l -n -f 5 22514 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22514.txt
./wave-skim -l -n -f 5 22515 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22515.txt
./wave-skim -l -n -f 5 22516 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22516.txt
./wave-skim -l -n -f 5 22517 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22517.txt
./wave-skim -l -n -f 5 22518 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22518.txt
./wave-skim -l -n -f 5 22519 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22519.txt
./wave-skim -l -n -f 5 22520 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22520.txt
./wave-skim -l -n -f 5 22521 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22521.txt
./wave-skim -l -n -f 5 22522 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22522.txt
./wave-skim -l -n -f 5 22523 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22523.txt
./wave-skim -l -n -f 5 22524 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22524.txt
./wave-skim -l -n -f 5 22525 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22525.txt
./wave-skim -l -n -f 5 22526 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22526.txt
./wave-skim -l -n -f 5 22527 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22527.txt
./wave-skim -l -n -f 5 22528 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22528.txt
./wave-skim -l -n -f 5 22529 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22529.txt
./wave-skim -l -n -f 5 22530 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22530.txt
./wave-skim -l -n -f 5 22531 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22531.txt
./wave-skim -l -n -f 5 22532 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22532.txt
./wave-skim -l -n -f 5 22533 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22533.txt
./wave-skim -l -n -f 5 22534 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22534.txt
./wave-skim -l -n -f 5 22535 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22535.txt
./wave-skim -l -n -f 5 22536 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22536.txt
./wave-skim -l -n -f 5 22537 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22537.txt
./wave-skim -l -n -f 5 22538 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22538.txt
./wave-skim -l -n -f 5 22539 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22539.txt
./wave-skim -l -n -f 5 22540 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22540.txt
./wave-skim -l -n -f 5 22541 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22541.txt
./wave-skim -l -n -f 5 22542 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22542.txt
./wave-skim -l -n -f 5 22543 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22543.txt
./wave-skim -l -n -f 5 22544 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22544.txt
./wave-skim -l -n -f 5 22545 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22545.txt
./wave-skim -l -n -f 5 22546 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22546.txt
./wave-skim -l -n -f 5 22547 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22547.txt
./wave-skim -l -n -f 5 22548 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22548.txt
./wave-skim -l -n -f 5 22549 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22549.txt
./wave-skim -l -n -f 5 22550 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22550.txt
./wave-skim -l -n -f 5 22551 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22551.txt
./wave-skim -l -n -f 5 22552 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22552.txt
./wave-skim -l -n -f 5 22553 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22553.txt
./wave-skim -l -n -f 5 22554 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22554.txt
./wave-skim -l -n -f 5 22555 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22555.txt
./wave-skim -l -n -f 5 22556 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22556.txt
./wave-skim -l -n -f 5 22557 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22557.txt
./wave-skim -l -n -f 5 22558 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22558.txt
./wave-skim -l -n -f 5 22559 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22559.txt
./wave-skim -l -n -f 5 22560 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22560.txt
./wave-skim -l -n -f 5 22561 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22561.txt
./wave-skim -l -n -f 5 22562 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22562.txt
./wave-skim -l -n -f 5 22563 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22563.txt
./wave-skim -l -n -f 5 22564 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22564.txt
./wave-skim -l -n -f 5 22565 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22565.txt
./wave-skim -l -n -f 5 22566 -p /global/projecta/projectdirs/majorana/users/wisecg/special/skim /global/projecta/projectdirs/majorana/users/wisecg/special/waves >& ./logs/wave-ds5-22566.txt
