./job-panda.py -sub 0 0 -split >& ./logs/split-ds0-0.txt
./job-panda.py -sub 0 1 -split >& ./logs/split-ds0-1.txt
./job-panda.py -sub 0 2 -split >& ./logs/split-ds0-2.txt
./job-panda.py -sub 0 3 -split >& ./logs/split-ds0-3.txt
./job-panda.py -sub 0 4 -split >& ./logs/split-ds0-4.txt
./job-panda.py -sub 0 5 -split >& ./logs/split-ds0-5.txt
./job-panda.py -sub 0 6 -split >& ./logs/split-ds0-6.txt
./job-panda.py -sub 0 7 -split >& ./logs/split-ds0-7.txt
./job-panda.py -sub 0 8 -split >& ./logs/split-ds0-8.txt
./job-panda.py -sub 0 9 -split >& ./logs/split-ds0-9.txt
./job-panda.py -sub 0 10 -split >& ./logs/split-ds0-10.txt
./job-panda.py -sub 0 11 -split >& ./logs/split-ds0-11.txt
./job-panda.py -sub 0 12 -split >& ./logs/split-ds0-12.txt
./job-panda.py -sub 0 13 -split >& ./logs/split-ds0-13.txt
./job-panda.py -sub 0 14 -split >& ./logs/split-ds0-14.txt
./job-panda.py -sub 0 15 -split >& ./logs/split-ds0-15.txt
./job-panda.py -sub 0 16 -split >& ./logs/split-ds0-16.txt
./job-panda.py -sub 0 17 -split >& ./logs/split-ds0-17.txt
./job-panda.py -sub 0 18 -split >& ./logs/split-ds0-18.txt
./job-panda.py -sub 0 19 -split >& ./logs/split-ds0-19.txt
./job-panda.py -sub 0 20 -split >& ./logs/split-ds0-20.txt
./job-panda.py -sub 0 21 -split >& ./logs/split-ds0-21.txt
./job-panda.py -sub 0 22 -split >& ./logs/split-ds0-22.txt
./job-panda.py -sub 0 23 -split >& ./logs/split-ds0-23.txt
./job-panda.py -sub 0 24 -split >& ./logs/split-ds0-24.txt
./job-panda.py -sub 0 25 -split >& ./logs/split-ds0-25.txt
./job-panda.py -sub 0 26 -split >& ./logs/split-ds0-26.txt
./job-panda.py -sub 0 27 -split >& ./logs/split-ds0-27.txt
./job-panda.py -sub 0 28 -split >& ./logs/split-ds0-28.txt
./job-panda.py -sub 0 29 -split >& ./logs/split-ds0-29.txt
./job-panda.py -sub 0 30 -split >& ./logs/split-ds0-30.txt
./job-panda.py -sub 0 31 -split >& ./logs/split-ds0-31.txt
./job-panda.py -sub 0 32 -split >& ./logs/split-ds0-32.txt
./job-panda.py -sub 0 33 -split >& ./logs/split-ds0-33.txt
./job-panda.py -sub 0 34 -split >& ./logs/split-ds0-34.txt
./job-panda.py -sub 0 35 -split >& ./logs/split-ds0-35.txt
./job-panda.py -sub 0 36 -split >& ./logs/split-ds0-36.txt
./job-panda.py -sub 0 37 -split >& ./logs/split-ds0-37.txt
./job-panda.py -sub 0 38 -split >& ./logs/split-ds0-38.txt
./job-panda.py -sub 0 39 -split >& ./logs/split-ds0-39.txt
./job-panda.py -sub 0 40 -split >& ./logs/split-ds0-40.txt
./job-panda.py -sub 0 41 -split >& ./logs/split-ds0-41.txt
./job-panda.py -sub 0 42 -split >& ./logs/split-ds0-42.txt
./job-panda.py -sub 0 43 -split >& ./logs/split-ds0-43.txt
./job-panda.py -sub 0 44 -split >& ./logs/split-ds0-44.txt
./job-panda.py -sub 0 45 -split >& ./logs/split-ds0-45.txt
./job-panda.py -sub 0 46 -split >& ./logs/split-ds0-46.txt
./job-panda.py -sub 0 47 -split >& ./logs/split-ds0-47.txt
./job-panda.py -sub 0 48 -split >& ./logs/split-ds0-48.txt
./job-panda.py -sub 0 49 -split >& ./logs/split-ds0-49.txt
./job-panda.py -sub 0 50 -split >& ./logs/split-ds0-50.txt
./job-panda.py -sub 0 51 -split >& ./logs/split-ds0-51.txt
./job-panda.py -sub 0 52 -split >& ./logs/split-ds0-52.txt
./job-panda.py -sub 0 53 -split >& ./logs/split-ds0-53.txt
./job-panda.py -sub 0 54 -split >& ./logs/split-ds0-54.txt
./job-panda.py -sub 0 55 -split >& ./logs/split-ds0-55.txt
./job-panda.py -sub 0 56 -split >& ./logs/split-ds0-56.txt
./job-panda.py -sub 0 57 -split >& ./logs/split-ds0-57.txt
./job-panda.py -sub 0 58 -split >& ./logs/split-ds0-58.txt
./job-panda.py -sub 0 59 -split >& ./logs/split-ds0-59.txt
./job-panda.py -sub 0 60 -split >& ./logs/split-ds0-60.txt
./job-panda.py -sub 0 61 -split >& ./logs/split-ds0-61.txt
./job-panda.py -sub 0 62 -split >& ./logs/split-ds0-62.txt
./job-panda.py -sub 0 63 -split >& ./logs/split-ds0-63.txt
./job-panda.py -sub 0 64 -split >& ./logs/split-ds0-64.txt
./job-panda.py -sub 0 65 -split >& ./logs/split-ds0-65.txt
./job-panda.py -sub 0 66 -split >& ./logs/split-ds0-66.txt
./job-panda.py -sub 0 67 -split >& ./logs/split-ds0-67.txt
./job-panda.py -sub 0 68 -split >& ./logs/split-ds0-68.txt
./job-panda.py -sub 0 69 -split >& ./logs/split-ds0-69.txt
./job-panda.py -sub 0 71 -split >& ./logs/split-ds0-71.txt
./job-panda.py -sub 0 72 -split >& ./logs/split-ds0-72.txt
./job-panda.py -sub 0 73 -split >& ./logs/split-ds0-73.txt
./job-panda.py -sub 0 74 -split >& ./logs/split-ds0-74.txt
./job-panda.py -sub 0 75 -split >& ./logs/split-ds0-75.txt
./job-panda.py -sub 1 0 -split >& ./logs/split-ds1-0.txt
./job-panda.py -sub 1 1 -split >& ./logs/split-ds1-1.txt
./job-panda.py -sub 1 2 -split >& ./logs/split-ds1-2.txt
./job-panda.py -sub 1 3 -split >& ./logs/split-ds1-3.txt
./job-panda.py -sub 1 4 -split >& ./logs/split-ds1-4.txt
./job-panda.py -sub 1 5 -split >& ./logs/split-ds1-5.txt
./job-panda.py -sub 1 6 -split >& ./logs/split-ds1-6.txt
./job-panda.py -sub 1 7 -split >& ./logs/split-ds1-7.txt
./job-panda.py -sub 1 9 -split >& ./logs/split-ds1-9.txt
./job-panda.py -sub 1 10 -split >& ./logs/split-ds1-10.txt
./job-panda.py -sub 1 11 -split >& ./logs/split-ds1-11.txt
./job-panda.py -sub 1 12 -split >& ./logs/split-ds1-12.txt
./job-panda.py -sub 1 13 -split >& ./logs/split-ds1-13.txt
./job-panda.py -sub 1 14 -split >& ./logs/split-ds1-14.txt
./job-panda.py -sub 1 15 -split >& ./logs/split-ds1-15.txt
./job-panda.py -sub 1 16 -split >& ./logs/split-ds1-16.txt
./job-panda.py -sub 1 17 -split >& ./logs/split-ds1-17.txt
./job-panda.py -sub 1 18 -split >& ./logs/split-ds1-18.txt
./job-panda.py -sub 1 19 -split >& ./logs/split-ds1-19.txt
./job-panda.py -sub 1 20 -split >& ./logs/split-ds1-20.txt
./job-panda.py -sub 1 21 -split >& ./logs/split-ds1-21.txt
./job-panda.py -sub 1 22 -split >& ./logs/split-ds1-22.txt
./job-panda.py -sub 1 23 -split >& ./logs/split-ds1-23.txt
./job-panda.py -sub 1 24 -split >& ./logs/split-ds1-24.txt
./job-panda.py -sub 1 25 -split >& ./logs/split-ds1-25.txt
./job-panda.py -sub 1 26 -split >& ./logs/split-ds1-26.txt
./job-panda.py -sub 1 27 -split >& ./logs/split-ds1-27.txt
./job-panda.py -sub 1 28 -split >& ./logs/split-ds1-28.txt
./job-panda.py -sub 1 29 -split >& ./logs/split-ds1-29.txt
./job-panda.py -sub 1 32 -split >& ./logs/split-ds1-32.txt
./job-panda.py -sub 1 34 -split >& ./logs/split-ds1-34.txt
./job-panda.py -sub 1 35 -split >& ./logs/split-ds1-35.txt
./job-panda.py -sub 1 36 -split >& ./logs/split-ds1-36.txt
./job-panda.py -sub 1 37 -split >& ./logs/split-ds1-37.txt
./job-panda.py -sub 1 38 -split >& ./logs/split-ds1-38.txt
./job-panda.py -sub 1 40 -split >& ./logs/split-ds1-40.txt
./job-panda.py -sub 1 41 -split >& ./logs/split-ds1-41.txt
./job-panda.py -sub 1 43 -split >& ./logs/split-ds1-43.txt
./job-panda.py -sub 1 44 -split >& ./logs/split-ds1-44.txt
./job-panda.py -sub 1 45 -split >& ./logs/split-ds1-45.txt
./job-panda.py -sub 1 46 -split >& ./logs/split-ds1-46.txt
./job-panda.py -sub 1 47 -split >& ./logs/split-ds1-47.txt
./job-panda.py -sub 1 50 -split >& ./logs/split-ds1-50.txt
./job-panda.py -sub 1 51 -split >& ./logs/split-ds1-51.txt
./job-panda.py -sub 2 0 -split >& ./logs/split-ds2-0.txt
./job-panda.py -sub 2 1 -split >& ./logs/split-ds2-1.txt
./job-panda.py -sub 2 2 -split >& ./logs/split-ds2-2.txt
./job-panda.py -sub 2 3 -split >& ./logs/split-ds2-3.txt
./job-panda.py -sub 2 4 -split >& ./logs/split-ds2-4.txt
./job-panda.py -sub 2 5 -split >& ./logs/split-ds2-5.txt
./job-panda.py -sub 2 6 -split >& ./logs/split-ds2-6.txt
./job-panda.py -sub 2 7 -split >& ./logs/split-ds2-7.txt
./job-panda.py -sub 3 0 -split >& ./logs/split-ds3-0.txt
./job-panda.py -sub 3 1 -split >& ./logs/split-ds3-1.txt
./job-panda.py -sub 3 2 -split >& ./logs/split-ds3-2.txt
./job-panda.py -sub 3 3 -split >& ./logs/split-ds3-3.txt
./job-panda.py -sub 3 4 -split >& ./logs/split-ds3-4.txt
./job-panda.py -sub 3 5 -split >& ./logs/split-ds3-5.txt
./job-panda.py -sub 3 6 -split >& ./logs/split-ds3-6.txt
./job-panda.py -sub 3 7 -split >& ./logs/split-ds3-7.txt
./job-panda.py -sub 3 8 -split >& ./logs/split-ds3-8.txt
./job-panda.py -sub 3 9 -split >& ./logs/split-ds3-9.txt
./job-panda.py -sub 3 10 -split >& ./logs/split-ds3-10.txt
./job-panda.py -sub 3 11 -split >& ./logs/split-ds3-11.txt
./job-panda.py -sub 3 12 -split >& ./logs/split-ds3-12.txt
./job-panda.py -sub 3 13 -split >& ./logs/split-ds3-13.txt
./job-panda.py -sub 3 14 -split >& ./logs/split-ds3-14.txt
./job-panda.py -sub 3 15 -split >& ./logs/split-ds3-15.txt
./job-panda.py -sub 3 16 -split >& ./logs/split-ds3-16.txt
./job-panda.py -sub 3 17 -split >& ./logs/split-ds3-17.txt
./job-panda.py -sub 3 18 -split >& ./logs/split-ds3-18.txt
./job-panda.py -sub 3 19 -split >& ./logs/split-ds3-19.txt
./job-panda.py -sub 3 20 -split >& ./logs/split-ds3-20.txt
./job-panda.py -sub 3 21 -split >& ./logs/split-ds3-21.txt
./job-panda.py -sub 3 22 -split >& ./logs/split-ds3-22.txt
./job-panda.py -sub 3 23 -split >& ./logs/split-ds3-23.txt
./job-panda.py -sub 3 24 -split >& ./logs/split-ds3-24.txt
./job-panda.py -sub 4 0 -split >& ./logs/split-ds4-0.txt
./job-panda.py -sub 4 3 -split >& ./logs/split-ds4-3.txt
./job-panda.py -sub 4 4 -split >& ./logs/split-ds4-4.txt
./job-panda.py -sub 4 6 -split >& ./logs/split-ds4-6.txt
./job-panda.py -sub 4 7 -split >& ./logs/split-ds4-7.txt
./job-panda.py -sub 4 8 -split >& ./logs/split-ds4-8.txt
./job-panda.py -sub 4 9 -split >& ./logs/split-ds4-9.txt
./job-panda.py -sub 4 10 -split >& ./logs/split-ds4-10.txt
./job-panda.py -sub 4 11 -split >& ./logs/split-ds4-11.txt
./job-panda.py -sub 4 12 -split >& ./logs/split-ds4-12.txt
./job-panda.py -sub 4 13 -split >& ./logs/split-ds4-13.txt
./job-panda.py -sub 4 14 -split >& ./logs/split-ds4-14.txt
./job-panda.py -sub 4 15 -split >& ./logs/split-ds4-15.txt
./job-panda.py -sub 4 16 -split >& ./logs/split-ds4-16.txt
./job-panda.py -sub 4 17 -split >& ./logs/split-ds4-17.txt
./job-panda.py -sub 4 18 -split >& ./logs/split-ds4-18.txt
./job-panda.py -sub 5 0 -split >& ./logs/split-ds5-0.txt
./job-panda.py -sub 5 1 -split >& ./logs/split-ds5-1.txt
./job-panda.py -sub 5 2 -split >& ./logs/split-ds5-2.txt
./job-panda.py -sub 5 3 -split >& ./logs/split-ds5-3.txt
./job-panda.py -sub 5 4 -split >& ./logs/split-ds5-4.txt
./job-panda.py -sub 5 5 -split >& ./logs/split-ds5-5.txt
./job-panda.py -sub 5 6 -split >& ./logs/split-ds5-6.txt
./job-panda.py -sub 5 7 -split >& ./logs/split-ds5-7.txt
./job-panda.py -sub 5 8 -split >& ./logs/split-ds5-8.txt
./job-panda.py -sub 5 9 -split >& ./logs/split-ds5-9.txt
./job-panda.py -sub 5 10 -split >& ./logs/split-ds5-10.txt
./job-panda.py -sub 5 11 -split >& ./logs/split-ds5-11.txt
./job-panda.py -sub 5 12 -split >& ./logs/split-ds5-12.txt
./job-panda.py -sub 5 13 -split >& ./logs/split-ds5-13.txt
./job-panda.py -sub 5 14 -split >& ./logs/split-ds5-14.txt
./job-panda.py -sub 5 15 -split >& ./logs/split-ds5-15.txt
./job-panda.py -sub 5 16 -split >& ./logs/split-ds5-16.txt
./job-panda.py -sub 5 17 -split >& ./logs/split-ds5-17.txt
./job-panda.py -sub 5 18 -split >& ./logs/split-ds5-18.txt
./job-panda.py -sub 5 19 -split >& ./logs/split-ds5-19.txt
./job-panda.py -sub 5 20 -split >& ./logs/split-ds5-20.txt
./job-panda.py -sub 5 21 -split >& ./logs/split-ds5-21.txt
./job-panda.py -sub 5 22 -split >& ./logs/split-ds5-22.txt
./job-panda.py -sub 5 23 -split >& ./logs/split-ds5-23.txt
./job-panda.py -sub 5 24 -split >& ./logs/split-ds5-24.txt
./job-panda.py -sub 5 25 -split >& ./logs/split-ds5-25.txt
./job-panda.py -sub 5 26 -split >& ./logs/split-ds5-26.txt
./job-panda.py -sub 5 27 -split >& ./logs/split-ds5-27.txt
./job-panda.py -sub 5 28 -split >& ./logs/split-ds5-28.txt
./job-panda.py -sub 5 29 -split >& ./logs/split-ds5-29.txt
./job-panda.py -sub 5 30 -split >& ./logs/split-ds5-30.txt
./job-panda.py -sub 5 31 -split >& ./logs/split-ds5-31.txt
./job-panda.py -sub 5 32 -split >& ./logs/split-ds5-32.txt
./job-panda.py -sub 5 33 -split >& ./logs/split-ds5-33.txt
./job-panda.py -sub 5 34 -split >& ./logs/split-ds5-34.txt
./job-panda.py -sub 5 35 -split >& ./logs/split-ds5-35.txt
./job-panda.py -sub 5 36 -split >& ./logs/split-ds5-36.txt
./job-panda.py -sub 5 37 -split >& ./logs/split-ds5-37.txt
./job-panda.py -sub 5 38 -split >& ./logs/split-ds5-38.txt
./job-panda.py -sub 5 39 -split >& ./logs/split-ds5-39.txt
./job-panda.py -sub 5 40 -split >& ./logs/split-ds5-40.txt
./job-panda.py -sub 5 41 -split >& ./logs/split-ds5-41.txt
./job-panda.py -sub 5 42 -split >& ./logs/split-ds5-42.txt
./job-panda.py -sub 5 43 -split >& ./logs/split-ds5-43.txt
./job-panda.py -sub 5 44 -split >& ./logs/split-ds5-44.txt
./job-panda.py -sub 5 45 -split >& ./logs/split-ds5-45.txt
./job-panda.py -sub 5 46 -split >& ./logs/split-ds5-46.txt
./job-panda.py -sub 5 47 -split >& ./logs/split-ds5-47.txt
./job-panda.py -sub 5 48 -split >& ./logs/split-ds5-48.txt
./job-panda.py -sub 5 49 -split >& ./logs/split-ds5-49.txt
./job-panda.py -sub 5 50 -split >& ./logs/split-ds5-50.txt
./job-panda.py -sub 5 51 -split >& ./logs/split-ds5-51.txt
./job-panda.py -sub 5 52 -split >& ./logs/split-ds5-52.txt
./job-panda.py -sub 5 53 -split >& ./logs/split-ds5-53.txt
./job-panda.py -sub 5 54 -split >& ./logs/split-ds5-54.txt
./job-panda.py -sub 5 55 -split >& ./logs/split-ds5-55.txt
./job-panda.py -sub 5 56 -split >& ./logs/split-ds5-56.txt
./job-panda.py -sub 5 57 -split >& ./logs/split-ds5-57.txt
./job-panda.py -sub 5 58 -split >& ./logs/split-ds5-58.txt
./job-panda.py -sub 5 59 -split >& ./logs/split-ds5-59.txt
./job-panda.py -sub 5 60 -split >& ./logs/split-ds5-60.txt
./job-panda.py -sub 5 61 -split >& ./logs/split-ds5-61.txt
./job-panda.py -sub 5 62 -split >& ./logs/split-ds5-62.txt
./job-panda.py -sub 5 63 -split >& ./logs/split-ds5-63.txt
./job-panda.py -sub 5 64 -split >& ./logs/split-ds5-64.txt
./job-panda.py -sub 5 65 -split >& ./logs/split-ds5-65.txt
./job-panda.py -sub 5 66 -split >& ./logs/split-ds5-66.txt
./job-panda.py -sub 5 67 -split >& ./logs/split-ds5-67.txt
./job-panda.py -sub 5 68 -split >& ./logs/split-ds5-68.txt
./job-panda.py -sub 5 69 -split >& ./logs/split-ds5-69.txt
./job-panda.py -sub 5 70 -split >& ./logs/split-ds5-70.txt
./job-panda.py -sub 5 71 -split >& ./logs/split-ds5-71.txt
./job-panda.py -sub 5 72 -split >& ./logs/split-ds5-72.txt
./job-panda.py -sub 5 73 -split >& ./logs/split-ds5-73.txt
./job-panda.py -sub 5 74 -split >& ./logs/split-ds5-74.txt
./job-panda.py -sub 5 75 -split >& ./logs/split-ds5-75.txt
./job-panda.py -sub 5 76 -split >& ./logs/split-ds5-76.txt
./job-panda.py -sub 5 77 -split >& ./logs/split-ds5-77.txt
./job-panda.py -sub 5 78 -split >& ./logs/split-ds5-78.txt
./job-panda.py -sub 5 79 -split >& ./logs/split-ds5-79.txt
./job-panda.py -sub 5 80 -split >& ./logs/split-ds5-80.txt
./job-panda.py -sub 5 81 -split >& ./logs/split-ds5-81.txt
./job-panda.py -sub 5 82 -split >& ./logs/split-ds5-82.txt
./job-panda.py -sub 5 83 -split >& ./logs/split-ds5-83.txt
./job-panda.py -sub 5 84 -split >& ./logs/split-ds5-84.txt
./job-panda.py -sub 5 85 -split >& ./logs/split-ds5-85.txt
./job-panda.py -sub 5 86 -split >& ./logs/split-ds5-86.txt
./job-panda.py -sub 5 87 -split >& ./logs/split-ds5-87.txt
./job-panda.py -sub 5 88 -split >& ./logs/split-ds5-88.txt
./job-panda.py -sub 5 89 -split >& ./logs/split-ds5-89.txt
./job-panda.py -sub 5 90 -split >& ./logs/split-ds5-90.txt
./job-panda.py -sub 5 91 -split >& ./logs/split-ds5-91.txt
./job-panda.py -sub 5 92 -split >& ./logs/split-ds5-92.txt
./job-panda.py -sub 5 93 -split >& ./logs/split-ds5-93.txt
./job-panda.py -sub 5 94 -split >& ./logs/split-ds5-94.txt
./job-panda.py -sub 5 95 -split >& ./logs/split-ds5-95.txt
./job-panda.py -sub 5 96 -split >& ./logs/split-ds5-96.txt
./job-panda.py -sub 5 97 -split >& ./logs/split-ds5-97.txt
./job-panda.py -sub 5 98 -split >& ./logs/split-ds5-98.txt
./job-panda.py -sub 5 99 -split >& ./logs/split-ds5-99.txt
./job-panda.py -sub 5 100 -split >& ./logs/split-ds5-100.txt
./job-panda.py -sub 5 101 -split >& ./logs/split-ds5-101.txt
./job-panda.py -sub 5 102 -split >& ./logs/split-ds5-102.txt
./job-panda.py -sub 5 103 -split >& ./logs/split-ds5-103.txt
./job-panda.py -sub 5 104 -split >& ./logs/split-ds5-104.txt
./job-panda.py -sub 5 105 -split >& ./logs/split-ds5-105.txt
./job-panda.py -sub 5 106 -split >& ./logs/split-ds5-106.txt
./job-panda.py -sub 5 107 -split >& ./logs/split-ds5-107.txt
./job-panda.py -sub 5 108 -split >& ./logs/split-ds5-108.txt
./job-panda.py -sub 5 109 -split >& ./logs/split-ds5-109.txt
./job-panda.py -sub 5 110 -split >& ./logs/split-ds5-110.txt
./job-panda.py -sub 5 111 -split >& ./logs/split-ds5-111.txt
./job-panda.py -sub 5 112 -split >& ./logs/split-ds5-112.txt
./job-panda.py -sub 5 113 -split >& ./logs/split-ds5-113.txt
./job-panda.py -sub 5 114 -split >& ./logs/split-ds5-114.txt
./job-panda.py -sub 5 115 -split >& ./logs/split-ds5-115.txt
./job-panda.py -sub 5 116 -split >& ./logs/split-ds5-116.txt
./job-panda.py -sub 5 118 -split >& ./logs/split-ds5-118.txt
./job-panda.py -sub 5 119 -split >& ./logs/split-ds5-119.txt
./job-panda.py -sub 5 120 -split >& ./logs/split-ds5-120.txt
./job-panda.py -sub 5 121 -split >& ./logs/split-ds5-121.txt
./job-panda.py -sub 6 0 -split >& ./logs/split-ds6-0.txt
./job-panda.py -sub 6 1 -split >& ./logs/split-ds6-1.txt
./job-panda.py -sub 6 2 -split >& ./logs/split-ds6-2.txt
./job-panda.py -sub 6 3 -split >& ./logs/split-ds6-3.txt
./job-panda.py -sub 6 5 -split >& ./logs/split-ds6-5.txt
./job-panda.py -sub 6 6 -split >& ./logs/split-ds6-6.txt
./job-panda.py -sub 6 7 -split >& ./logs/split-ds6-7.txt
./job-panda.py -sub 6 9 -split >& ./logs/split-ds6-9.txt
./job-panda.py -sub 6 10 -split >& ./logs/split-ds6-10.txt
./job-panda.py -sub 6 11 -split >& ./logs/split-ds6-11.txt
./job-panda.py -sub 6 12 -split >& ./logs/split-ds6-12.txt
./job-panda.py -sub 6 13 -split >& ./logs/split-ds6-13.txt
./job-panda.py -sub 6 14 -split >& ./logs/split-ds6-14.txt
./job-panda.py -sub 6 15 -split >& ./logs/split-ds6-15.txt
./job-panda.py -sub 6 16 -split >& ./logs/split-ds6-16.txt
./job-panda.py -sub 6 17 -split >& ./logs/split-ds6-17.txt
./job-panda.py -sub 6 18 -split >& ./logs/split-ds6-18.txt
./job-panda.py -sub 6 19 -split >& ./logs/split-ds6-19.txt
./job-panda.py -sub 6 20 -split >& ./logs/split-ds6-20.txt
./job-panda.py -sub 6 21 -split >& ./logs/split-ds6-21.txt
./job-panda.py -sub 6 22 -split >& ./logs/split-ds6-22.txt
./job-panda.py -sub 6 23 -split >& ./logs/split-ds6-23.txt
./job-panda.py -sub 6 24 -split >& ./logs/split-ds6-24.txt
./job-panda.py -sub 6 25 -split >& ./logs/split-ds6-25.txt
./job-panda.py -sub 6 26 -split >& ./logs/split-ds6-26.txt
./job-panda.py -sub 6 28 -split >& ./logs/split-ds6-28.txt
./job-panda.py -sub 6 29 -split >& ./logs/split-ds6-29.txt
./job-panda.py -sub 6 30 -split >& ./logs/split-ds6-30.txt
./job-panda.py -sub 6 31 -split >& ./logs/split-ds6-31.txt
./job-panda.py -sub 6 32 -split >& ./logs/split-ds6-32.txt
./job-panda.py -sub 6 33 -split >& ./logs/split-ds6-33.txt
./job-panda.py -sub 6 34 -split >& ./logs/split-ds6-34.txt
./job-panda.py -sub 6 36 -split >& ./logs/split-ds6-36.txt
./job-panda.py -sub 6 37 -split >& ./logs/split-ds6-37.txt
./job-panda.py -sub 6 38 -split >& ./logs/split-ds6-38.txt
./job-panda.py -sub 6 39 -split >& ./logs/split-ds6-39.txt
./job-panda.py -sub 6 41 -split >& ./logs/split-ds6-41.txt
./job-panda.py -sub 6 42 -split >& ./logs/split-ds6-42.txt
./job-panda.py -sub 6 43 -split >& ./logs/split-ds6-43.txt
