./job-panda.py -sub 0 70 -split >& ./logs/split-ds0-70.txt
./job-panda.py -sub 1 8 -split >& ./logs/split-ds1-8.txt
./job-panda.py -sub 1 30 -split >& ./logs/split-ds1-30.txt
./job-panda.py -sub 1 31 -split >& ./logs/split-ds1-31.txt
./job-panda.py -sub 1 33 -split >& ./logs/split-ds1-33.txt
./job-panda.py -sub 1 39 -split >& ./logs/split-ds1-39.txt
./job-panda.py -sub 1 42 -split >& ./logs/split-ds1-42.txt
./job-panda.py -sub 1 48 -split >& ./logs/split-ds1-48.txt
./job-panda.py -sub 1 49 -split >& ./logs/split-ds1-49.txt
./job-panda.py -sub 4 1 -split >& ./logs/split-ds4-1.txt
./job-panda.py -sub 4 2 -split >& ./logs/split-ds4-2.txt
./job-panda.py -sub 4 5 -split >& ./logs/split-ds4-5.txt
./job-panda.py -sub 5 113 -split >& ./logs/split-ds5-113.txt
./job-panda.py -sub 5 114 -split >& ./logs/split-ds5-114.txt
./job-panda.py -sub 5 115 -split >& ./logs/split-ds5-115.txt
./job-panda.py -sub 5 116 -split >& ./logs/split-ds5-116.txt
./job-panda.py -sub 5 117 -split >& ./logs/split-ds5-117.txt
./job-panda.py -sub 5 118 -split >& ./logs/split-ds5-118.txt
./job-panda.py -sub 5 119 -split >& ./logs/split-ds5-119.txt
./job-panda.py -sub 5 120 -split >& ./logs/split-ds5-120.txt
./job-panda.py -sub 5 121 -split >& ./logs/split-ds5-121.txt
./job-panda.py -sub 6 0 -split >& ./logs/split-ds6-0.txt
./job-panda.py -sub 6 1 -split >& ./logs/split-ds6-1.txt
./job-panda.py -sub 6 2 -split >& ./logs/split-ds6-2.txt
./job-panda.py -sub 6 3 -split >& ./logs/split-ds6-3.txt
./job-panda.py -sub 6 4 -split >& ./logs/split-ds6-4.txt
./job-panda.py -sub 6 5 -split >& ./logs/split-ds6-5.txt
./job-panda.py -sub 6 6 -split >& ./logs/split-ds6-6.txt
./job-panda.py -sub 6 7 -split >& ./logs/split-ds6-7.txt
./job-panda.py -sub 6 8 -split >& ./logs/split-ds6-8.txt
./job-panda.py -sub 6 9 -split >& ./logs/split-ds6-9.txt
./job-panda.py -sub 6 10 -split >& ./logs/split-ds6-10.txt
./job-panda.py -sub 6 11 -split >& ./logs/split-ds6-11.txt
./job-panda.py -sub 6 12 -split >& ./logs/split-ds6-12.txt
./job-panda.py -sub 6 13 -split >& ./logs/split-ds6-13.txt
./job-panda.py -sub 6 14 -split >& ./logs/split-ds6-14.txt
./job-panda.py -sub 6 15 -split >& ./logs/split-ds6-15.txt
./job-panda.py -sub 6 16 -split >& ./logs/split-ds6-16.txt
./job-panda.py -sub 6 17 -split >& ./logs/split-ds6-17.txt
./job-panda.py -sub 6 18 -split >& ./logs/split-ds6-18.txt
./job-panda.py -sub 6 19 -split >& ./logs/split-ds6-19.txt
./job-panda.py -sub 6 20 -split >& ./logs/split-ds6-20.txt
./job-panda.py -sub 6 21 -split >& ./logs/split-ds6-21.txt
./job-panda.py -sub 6 22 -split >& ./logs/split-ds6-22.txt
./job-panda.py -sub 6 23 -split >& ./logs/split-ds6-23.txt
./job-panda.py -sub 6 24 -split >& ./logs/split-ds6-24.txt
./job-panda.py -sub 6 25 -split >& ./logs/split-ds6-25.txt
./job-panda.py -sub 6 26 -split >& ./logs/split-ds6-26.txt
./job-panda.py -sub 6 27 -split >& ./logs/split-ds6-27.txt
./job-panda.py -sub 6 28 -split >& ./logs/split-ds6-28.txt
./job-panda.py -sub 6 29 -split >& ./logs/split-ds6-29.txt
./job-panda.py -sub 6 30 -split >& ./logs/split-ds6-30.txt
./job-panda.py -sub 6 31 -split >& ./logs/split-ds6-31.txt
./job-panda.py -sub 6 32 -split >& ./logs/split-ds6-32.txt
./job-panda.py -sub 6 33 -split >& ./logs/split-ds6-33.txt
./job-panda.py -sub 6 34 -split >& ./logs/split-ds6-34.txt
./job-panda.py -sub 6 35 -split >& ./logs/split-ds6-35.txt
./job-panda.py -sub 6 36 -split >& ./logs/split-ds6-36.txt
./job-panda.py -sub 6 37 -split >& ./logs/split-ds6-37.txt
./job-panda.py -sub 6 38 -split >& ./logs/split-ds6-38.txt
./job-panda.py -sub 6 39 -split >& ./logs/split-ds6-39.txt
./job-panda.py -sub 6 40 -split >& ./logs/split-ds6-40.txt
./job-panda.py -sub 6 41 -split >& ./logs/split-ds6-41.txt
./job-panda.py -sub 6 42 -split >& ./logs/split-ds6-42.txt
./job-panda.py -sub 6 43 -split >& ./logs/split-ds6-43.txt
