./wave-skim -n  -r 5 113 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds5-113.txt
./wave-skim -n  -r 5 114 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds5-114.txt
./wave-skim -n  -r 5 115 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds5-115.txt
./wave-skim -n  -r 5 116 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds5-116.txt
./wave-skim -n  -r 5 117 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds5-117.txt
./wave-skim -n  -r 5 118 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds5-118.txt
./wave-skim -n  -r 5 119 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds5-119.txt
./wave-skim -n  -r 5 120 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds5-120.txt
./wave-skim -n  -r 5 121 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds5-121.txt
./wave-skim -n  -r 6 0 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-0.txt
./wave-skim -n  -r 6 1 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-1.txt
./wave-skim -n  -r 6 2 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-2.txt
./wave-skim -n  -r 6 3 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-3.txt
./wave-skim -n  -r 6 4 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-4.txt
./wave-skim -n  -r 6 5 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-5.txt
./wave-skim -n  -r 6 6 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-6.txt
./wave-skim -n  -r 6 7 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-7.txt
./wave-skim -n  -r 6 8 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-8.txt
./wave-skim -n  -r 6 9 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-9.txt
./wave-skim -n  -r 6 10 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-10.txt
./wave-skim -n  -r 6 11 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-11.txt
./wave-skim -n  -r 6 12 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-12.txt
./wave-skim -n  -r 6 13 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-13.txt
./wave-skim -n  -r 6 14 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-14.txt
./wave-skim -n  -r 6 15 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-15.txt
./wave-skim -n  -r 6 16 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-16.txt
./wave-skim -n  -r 6 17 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-17.txt
./wave-skim -n  -r 6 18 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-18.txt
./wave-skim -n  -r 6 19 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-19.txt
./wave-skim -n  -r 6 20 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-20.txt
./wave-skim -n  -r 6 21 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-21.txt
./wave-skim -n  -r 6 22 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-22.txt
./wave-skim -n  -r 6 23 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-23.txt
./wave-skim -n  -r 6 24 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-24.txt
./wave-skim -n  -r 6 25 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-25.txt
./wave-skim -n  -r 6 26 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-26.txt
./wave-skim -n  -r 6 27 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-27.txt
./wave-skim -n  -r 6 28 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-28.txt
./wave-skim -n  -r 6 29 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-29.txt
./wave-skim -n  -r 6 30 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-30.txt
./wave-skim -n  -r 6 31 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-31.txt
./wave-skim -n  -r 6 32 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-32.txt
./wave-skim -n  -r 6 33 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-33.txt
./wave-skim -n  -r 6 34 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-34.txt
./wave-skim -n  -r 6 35 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-35.txt
./wave-skim -n  -r 6 36 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-36.txt
./wave-skim -n  -r 6 37 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-37.txt
./wave-skim -n  -r 6 38 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-38.txt
./wave-skim -n  -r 6 39 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-39.txt
./wave-skim -n  -r 6 40 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-40.txt
./wave-skim -n  -r 6 41 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-41.txt
./wave-skim -n  -r 6 42 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-42.txt
./wave-skim -n  -r 6 43 -p /global/projecta/projectdirs/majorana/users/wisecg/bkg/skim /global/projecta/projectdirs/majorana/users/wisecg/bkg/waves >& ./logs/wave-ds6-43.txt
