./wave-skim -n  -c -f 5 23960 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run23960.txt
./wave-skim -n  -c -f 5 23961 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run23961.txt
./wave-skim -n  -c -f 5 23962 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run23962.txt
./wave-skim -n  -c -f 5 23963 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run23963.txt
./wave-skim -n  -c -f 5 23964 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run23964.txt
./wave-skim -n  -c -f 5 23965 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run23965.txt
./wave-skim -n  -c -f 5 23966 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run23966.txt
./wave-skim -n  -c -f 5 23967 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run23967.txt
./wave-skim -n  -c -f 5 23968 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run23968.txt
./wave-skim -n  -c -f 5 23969 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run23969.txt
./wave-skim -n  -c -f 5 23970 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run23970.txt
./wave-skim -n  -c -f 5 24305 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24305.txt
./wave-skim -n  -c -f 5 24306 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24306.txt
./wave-skim -n  -c -f 5 24307 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24307.txt
./wave-skim -n  -c -f 5 24308 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24308.txt
./wave-skim -n  -c -f 5 24309 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24309.txt
./wave-skim -n  -c -f 5 24310 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24310.txt
./wave-skim -n  -c -f 5 24311 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24311.txt
./wave-skim -n  -c -f 5 24312 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24312.txt
./wave-skim -n  -c -f 5 24313 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24313.txt
./wave-skim -n  -c -f 5 24314 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24314.txt
./wave-skim -n  -c -f 5 24315 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24315.txt
./wave-skim -n  -c -f 5 24316 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24316.txt
./wave-skim -n  -c -f 5 24317 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24317.txt
./wave-skim -n  -c -f 5 24318 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24318.txt
./wave-skim -n  -c -f 5 24322 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24322.txt
./wave-skim -n  -c -f 5 24323 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24323.txt
./wave-skim -n  -c -f 5 24324 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24324.txt
./wave-skim -n  -c -f 5 24325 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24325.txt
./wave-skim -n  -c -f 5 24326 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24326.txt
./wave-skim -n  -c -f 5 24327 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24327.txt
./wave-skim -n  -c -f 5 24328 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24328.txt
./wave-skim -n  -c -f 5 24329 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24329.txt
./wave-skim -n  -c -f 5 24330 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24330.txt
./wave-skim -n  -c -f 5 24331 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24331.txt
./wave-skim -n  -c -f 5 24332 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24332.txt
./wave-skim -n  -c -f 5 24539 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24539.txt
./wave-skim -n  -c -f 5 24540 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24540.txt
./wave-skim -n  -c -f 5 24541 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24541.txt
./wave-skim -n  -c -f 5 24542 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24542.txt
./wave-skim -n  -c -f 5 24543 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24543.txt
./wave-skim -n  -c -f 5 24544 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24544.txt
./wave-skim -n  -c -f 5 24545 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24545.txt
./wave-skim -n  -c -f 5 24546 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24546.txt
./wave-skim -n  -c -f 5 24547 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24547.txt
./wave-skim -n  -c -f 5 24548 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24548.txt
./wave-skim -n  -c -f 5 24549 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24549.txt
./wave-skim -n  -c -f 5 24550 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24550.txt
./wave-skim -n  -c -f 5 24551 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24551.txt
./wave-skim -n  -c -f 5 24552 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24552.txt
./wave-skim -n  -c -f 5 24556 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24556.txt
./wave-skim -n  -c -f 5 24557 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24557.txt
./wave-skim -n  -c -f 5 24558 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24558.txt
./wave-skim -n  -c -f 5 24559 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24559.txt
./wave-skim -n  -c -f 5 24560 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24560.txt
./wave-skim -n  -c -f 5 24561 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24561.txt
./wave-skim -n  -c -f 5 24562 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24562.txt
./wave-skim -n  -c -f 5 24563 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24563.txt
./wave-skim -n  -c -f 5 24564 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24564.txt
./wave-skim -n  -c -f 5 24565 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24565.txt
./wave-skim -n  -c -f 5 24566 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24566.txt
./wave-skim -n  -c -f 5 24761 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24761.txt
./wave-skim -n  -c -f 5 24762 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24762.txt
./wave-skim -n  -c -f 5 24763 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24763.txt
./wave-skim -n  -c -f 5 24764 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24764.txt
./wave-skim -n  -c -f 5 24765 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24765.txt
./wave-skim -n  -c -f 5 24766 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24766.txt
./wave-skim -n  -c -f 5 24767 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24767.txt
./wave-skim -n  -c -f 5 24768 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24768.txt
./wave-skim -n  -c -f 5 24769 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24769.txt
./wave-skim -n  -c -f 5 24770 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24770.txt
./wave-skim -n  -c -f 5 24771 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24771.txt
./wave-skim -n  -c -f 5 24772 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24772.txt
./wave-skim -n  -c -f 5 24773 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24773.txt
./wave-skim -n  -c -f 5 24774 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24774.txt
./wave-skim -n  -c -f 5 24775 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24775.txt
./wave-skim -n  -c -f 5 24779 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24779.txt
./wave-skim -n  -c -f 5 24780 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24780.txt
./wave-skim -n  -c -f 5 24781 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24781.txt
./wave-skim -n  -c -f 5 24782 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24782.txt
./wave-skim -n  -c -f 5 24783 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24783.txt
./wave-skim -n  -c -f 5 24784 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24784.txt
./wave-skim -n  -c -f 5 24785 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24785.txt
./wave-skim -n  -c -f 5 24786 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24786.txt
./wave-skim -n  -c -f 5 24787 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24787.txt
./wave-skim -n  -c -f 5 24788 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24788.txt
./wave-skim -n  -c -f 5 24789 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24789.txt
./wave-skim -n  -c -f 5 24971 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24971.txt
./wave-skim -n  -c -f 5 24972 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24972.txt
./wave-skim -n  -c -f 5 24973 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24973.txt
./wave-skim -n  -c -f 5 24974 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24974.txt
./wave-skim -n  -c -f 5 24975 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24975.txt
./wave-skim -n  -c -f 5 24976 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24976.txt
./wave-skim -n  -c -f 5 24977 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24977.txt
./wave-skim -n  -c -f 5 24978 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24978.txt
./wave-skim -n  -c -f 5 24979 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24979.txt
./wave-skim -n  -c -f 5 24980 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24980.txt
./wave-skim -n  -c -f 5 24981 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24981.txt
./wave-skim -n  -c -f 5 24982 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24982.txt
./wave-skim -n  -c -f 5 24983 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24983.txt
./wave-skim -n  -c -f 5 24984 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24984.txt
./wave-skim -n  -c -f 5 24988 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24988.txt
./wave-skim -n  -c -f 5 24989 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24989.txt
./wave-skim -n  -c -f 5 24990 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24990.txt
./wave-skim -n  -c -f 5 24991 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24991.txt
./wave-skim -n  -c -f 5 24992 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24992.txt
./wave-skim -n  -c -f 5 24993 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24993.txt
./wave-skim -n  -c -f 5 24994 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24994.txt
./wave-skim -n  -c -f 5 24995 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24995.txt
./wave-skim -n  -c -f 5 24996 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24996.txt
./wave-skim -n  -c -f 5 24997 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24997.txt
./wave-skim -n  -c -f 5 24998 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run24998.txt
./wave-skim -n  -c -f 5 25248 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25248.txt
./wave-skim -n  -c -f 5 25249 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25249.txt
./wave-skim -n  -c -f 5 25250 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25250.txt
./wave-skim -n  -c -f 5 25251 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25251.txt
./wave-skim -n  -c -f 5 25252 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25252.txt
./wave-skim -n  -c -f 5 25253 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25253.txt
./wave-skim -n  -c -f 5 25254 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25254.txt
./wave-skim -n  -c -f 5 25255 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25255.txt
./wave-skim -n  -c -f 5 25256 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25256.txt
./wave-skim -n  -c -f 5 25257 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25257.txt
./wave-skim -n  -c -f 5 25258 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25258.txt
./wave-skim -n  -c -f 5 25259 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25259.txt
./wave-skim -n  -c -f 5 25260 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25260.txt
./wave-skim -n  -c -f 5 25261 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25261.txt
./wave-skim -n  -c -f 5 25265 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25265.txt
./wave-skim -n  -c -f 5 25266 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25266.txt
./wave-skim -n  -c -f 5 25267 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25267.txt
./wave-skim -n  -c -f 5 25268 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25268.txt
./wave-skim -n  -c -f 5 25269 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25269.txt
./wave-skim -n  -c -f 5 25270 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25270.txt
./wave-skim -n  -c -f 5 25271 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25271.txt
./wave-skim -n  -c -f 5 25272 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25272.txt
./wave-skim -n  -c -f 5 25273 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25273.txt
./wave-skim -n  -c -f 5 25274 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25274.txt
./wave-skim -n  -c -f 5 25275 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25275.txt
./wave-skim -n  -c -f 5 25479 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25479.txt
./wave-skim -n  -c -f 5 25480 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25480.txt
./wave-skim -n  -c -f 5 25481 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25481.txt
./wave-skim -n  -c -f 5 25482 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25482.txt
./wave-skim -n  -c -f 5 25483 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25483.txt
./wave-skim -n  -c -f 5 25484 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25484.txt
./wave-skim -n  -c -f 5 25485 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25485.txt
./wave-skim -n  -c -f 5 25486 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25486.txt
./wave-skim -n  -c -f 5 25487 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25487.txt
./wave-skim -n  -c -f 5 25488 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25488.txt
./wave-skim -n  -c -f 5 25489 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25489.txt
./wave-skim -n  -c -f 5 25490 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25490.txt
./wave-skim -n  -c -f 5 25491 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25491.txt
./wave-skim -n  -c -f 5 25492 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25492.txt
./wave-skim -n  -c -f 5 25496 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25496.txt
./wave-skim -n  -c -f 5 25497 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25497.txt
./wave-skim -n  -c -f 5 25498 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25498.txt
./wave-skim -n  -c -f 5 25499 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25499.txt
./wave-skim -n  -c -f 5 25500 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25500.txt
./wave-skim -n  -c -f 5 25501 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25501.txt
./wave-skim -n  -c -f 5 25502 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25502.txt
./wave-skim -n  -c -f 5 25503 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25503.txt
./wave-skim -n  -c -f 5 25504 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25504.txt
./wave-skim -n  -c -f 5 25505 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25505.txt
./wave-skim -n  -c -f 5 25506 -p /global/projecta/projectdirs/majorana/users/wisecg/cal/skim /global/projecta/projectdirs/majorana/users/wisecg/cal/waves >& ./logs/wave-ds5-run25506.txt