./skim_mjd_data -f 22513 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22513.txt
./skim_mjd_data -f 22514 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22514.txt
./skim_mjd_data -f 22515 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22515.txt
./skim_mjd_data -f 22516 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22516.txt
./skim_mjd_data -f 22517 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22517.txt
./skim_mjd_data -f 22518 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22518.txt
./skim_mjd_data -f 22519 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22519.txt
./skim_mjd_data -f 22520 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22520.txt
./skim_mjd_data -f 22521 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22521.txt
./skim_mjd_data -f 22522 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22522.txt
./skim_mjd_data -f 22523 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22523.txt
./skim_mjd_data -f 22524 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22524.txt
./skim_mjd_data -f 22525 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22525.txt
./skim_mjd_data -f 22526 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22526.txt
./skim_mjd_data -f 22527 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22527.txt
./skim_mjd_data -f 22528 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22528.txt
./skim_mjd_data -f 22529 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22529.txt
./skim_mjd_data -f 22530 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22530.txt
./skim_mjd_data -f 22531 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22531.txt
./skim_mjd_data -f 22532 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22532.txt
./skim_mjd_data -f 22533 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22533.txt
./skim_mjd_data -f 22534 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22534.txt
./skim_mjd_data -f 22535 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22535.txt
./skim_mjd_data -f 22536 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22536.txt
./skim_mjd_data -f 22537 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22537.txt
./skim_mjd_data -f 22538 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22538.txt
./skim_mjd_data -f 22539 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22539.txt
./skim_mjd_data -f 22540 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22540.txt
./skim_mjd_data -f 22541 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22541.txt
./skim_mjd_data -f 22542 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22542.txt
./skim_mjd_data -f 22543 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22543.txt
./skim_mjd_data -f 22544 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22544.txt
./skim_mjd_data -f 22545 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22545.txt
./skim_mjd_data -f 22546 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22546.txt
./skim_mjd_data -f 22547 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22547.txt
./skim_mjd_data -f 22548 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22548.txt
./skim_mjd_data -f 22549 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22549.txt
./skim_mjd_data -f 22550 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22550.txt
./skim_mjd_data -f 22551 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22551.txt
./skim_mjd_data -f 22552 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22552.txt
./skim_mjd_data -f 22553 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22553.txt
./skim_mjd_data -f 22554 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22554.txt
./skim_mjd_data -f 22555 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22555.txt
./skim_mjd_data -f 22556 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22556.txt
./skim_mjd_data -f 22557 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22557.txt
./skim_mjd_data -f 22558 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22558.txt
./skim_mjd_data -f 22559 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22559.txt
./skim_mjd_data -f 22560 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22560.txt
./skim_mjd_data -f 22561 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22561.txt
./skim_mjd_data -f 22562 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22562.txt
./skim_mjd_data -f 22563 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22563.txt
./skim_mjd_data -f 22564 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22564.txt
./skim_mjd_data -f 22565 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22565.txt
./skim_mjd_data -f 22566 -l -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/special/skim >& ./logs/specialSkim-DS5-22566.txt
