./skim_mjd_data -f 9453 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9453.txt
./skim_mjd_data -f 9454 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9454.txt
./skim_mjd_data -f 9456 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9456.txt
./skim_mjd_data -f 9457 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9457.txt
./skim_mjd_data -f 9458 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9458.txt
./skim_mjd_data -f 9459 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9459.txt
./skim_mjd_data -f 9460 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9460.txt
./skim_mjd_data -f 9461 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9461.txt
./skim_mjd_data -f 9462 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9462.txt
./skim_mjd_data -f 9463 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9463.txt
./skim_mjd_data -f 9464 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9464.txt
./skim_mjd_data -f 9465 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9465.txt
./skim_mjd_data -f 9466 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9466.txt
./skim_mjd_data -f 9467 -l -g -d -t 0.7 /global/projecta/projectdirs/majorana/users/wisecg/cal/skim >& ./logs/skim-ds1-run9467.txt